version: '3.4'

volumes:
  dbdata:

services:
  db:
    image: mariadb:latest
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: udoit3
      MYSQL_USER: udoit
      MYSQL_PASSWORD: udoit
    ports:
      - "3306:3306"
  php:
    environment:
      DATABASE_URL: mysql://udoit:udoit@db:3306/udoit3
    ports:
      - "9000:9000"
    depends_on:
      - db
    build:
      context: ./
      dockerfile: ./Dockerfile
    links:
      - db
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html/src
      - ./config:/var/www/html/config
      - ./public:/var/www/html/public
      - ./.env:/var/www/html/.env
      - ./.env.local:/var/www/html/.env.local
      - ./bin:/var/www/html/bin

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    links:
      - php
    depends_on:
      - php
