version: '3.4'

volumes:
  site_volume:
  dbdata:

services:
  db:
    image: mysql:latest
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: udoit3
      MYSQL_USER: udoit
      MYSQL_PASSWORD: udoit
    ports:
      - "3306:3306"
  php:
    environment:
      DATABASE_URL: mysql://udoit:udoit@db:3306/udoit3
    ports:
      - "9000:9000"
    depends_on:
      - db
    build:
      context: ./
      dockerfile: ./Dockerfile
    links:
      - db
    working_dir: /var/www/html
    volumes:
      - site_volume:/var/www/html

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - site_volume:/var/www/html
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    links:
      - php
    depends_on:
      - php
